// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfgnpknmuoybpnvlptoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mZ25wa25tdW95YnBudmxwdG95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMjgzNTEsImV4cCI6MjA2MjkwNDM1MX0.PtbhBab_yq-Oj8W_xA33TbWNsFLWMh0EABHKqCbVxho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);